<?php


namespace Blog\Twig;

use Psr\Http\Message\ServerRequestInterface;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;


// класс который будет использовать Twig
// для корректного пути к файлам из любой точки сайта
class AssetExtentsion extends AbstractExtension
{

    private ServerRequestInterface $request;

    public function __construct(ServerRequestInterface $request){
        $this->request = $request;
    }


    public function getFunctions()
    {
        return [
            new TwigFunction('asset_url', [$this, 'getAssetUrl']),  // TODO: Change the autogenerated stub
            new TwigFunction('url', [$this, 'getUrl']), // TODO: Change the autogenerated stub
            new TwigFunction('base_url', [$this, 'getBaseUrl']), // TODO: Change the autogenerated stub
        ];
    }

    /**
     * @return string
     */
    public function getBaseUrl() : string {
        $params = $this->request->getServerParams();
        return $params['REQUEST_SCHEME'] . "://" . $params['HTTP_HOST'] . '/';
    }

    /**
     * @param string $path
     * @return string
     */
    public function getAssetUrl(string $path) : string{
        //return 'http://fitlent.web.blog.two/' . $path;
        return $this->getBaseUrl() . $path;
    }


    /**
     * @param string $path
     * @return string
     */
    public function getUrl(string $path) : string {
        return $this->getBaseUrl() . $path;
    }

}